-- Pixel placement log (append-only)
CREATE TABLE pixels (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    x             INTEGER          NOT NULL,
    y             INTEGER          NOT NULL,
    palette_index INTEGER          NOT NULL,
    author_uuid   VARCHAR(255)     NOT NULL,
    placed_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_pixel_xy ON pixels (x, y);

-- User identity mapping
CREATE TABLE users (
    uuid     VARCHAR(255) NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE
);
